// Auto-generated by HARVEST's emit_build_features tool. Do not edit.
// Reads CARGO_FEATURE_* variables (set by --features / Cargo.toml)
// and emits cargo:rustc-cfg / cargo:rustc-env directives.

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    println!("cargo:rustc-check-cfg=cfg(APP_MODE_fast, APP_MODE_safe)");
    let has_app_mode_fast = std::env::var("CARGO_FEATURE_APP_MODE_FAST").is_ok();
    let has_app_mode_safe = std::env::var("CARGO_FEATURE_APP_MODE_SAFE").is_ok();
    let app_mode_active = has_app_mode_fast as u32 + has_app_mode_safe as u32;
    if app_mode_active == 0 { panic!("one of APP_MODE_fast, APP_MODE_safe must be enabled"); }
    if app_mode_active > 1 { panic!("features APP_MODE_fast, APP_MODE_safe are mutually exclusive"); }
    let app_mode_value: &str = if has_app_mode_fast { println!("cargo:rustc-cfg=APP_MODE_fast"); "fast" } else if has_app_mode_safe { println!("cargo:rustc-cfg=APP_MODE_safe"); "safe" } else { unreachable!() };

    println!("cargo:rustc-check-cfg=cfg(BACKEND_alpha, BACKEND_beta)");
    let has_backend_alpha = std::env::var("CARGO_FEATURE_BACKEND_ALPHA").is_ok();
    let has_backend_beta = std::env::var("CARGO_FEATURE_BACKEND_BETA").is_ok();
    let backend_active = has_backend_alpha as u32 + has_backend_beta as u32;
    if backend_active == 0 { panic!("one of BACKEND_alpha, BACKEND_beta must be enabled"); }
    if backend_active > 1 { panic!("features BACKEND_alpha, BACKEND_beta are mutually exclusive"); }
    let backend_value: &str = if has_backend_alpha { println!("cargo:rustc-cfg=BACKEND_alpha"); "alpha" } else if has_backend_beta { println!("cargo:rustc-cfg=BACKEND_beta"); "beta" } else { unreachable!() };

    println!("cargo:rustc-check-cfg=cfg(WORD_SIZE_32, WORD_SIZE_64)");
    let has_word_size_32 = std::env::var("CARGO_FEATURE_WORD_SIZE_32").is_ok();
    let has_word_size_64 = std::env::var("CARGO_FEATURE_WORD_SIZE_64").is_ok();
    let word_size_active = has_word_size_32 as u32 + has_word_size_64 as u32;
    if word_size_active == 0 { panic!("one of WORD_SIZE_32, WORD_SIZE_64 must be enabled"); }
    if word_size_active > 1 { panic!("features WORD_SIZE_32, WORD_SIZE_64 are mutually exclusive"); }
    let word_size_value: &str = if has_word_size_32 { println!("cargo:rustc-cfg=WORD_SIZE_32"); "32" } else if has_word_size_64 { println!("cargo:rustc-cfg=WORD_SIZE_64"); "64" } else { unreachable!() };

    println!("cargo:rustc-env=APP_MODE_STR={}", app_mode_value);
    println!("cargo:rustc-env=WORD_SIZE={}", word_size_value);
    println!("cargo:rustc-env=BUILD_PROFILE={}_{}", backend_value, word_size_value);
}
