//! Renders a deterministic `build.rs` from a [`BuildConfigIR`].
//!
//! The generated script:
//!
//! - Declares every cfg name it might set with `cargo:rustc-check-cfg=cfg(...)`
//!   so rustc does not warn about unknown configs.
//! - For each enum variable, reads `CARGO_FEATURE_VAR_VALUE` environment vars
//!   (Cargo uppercases the feature name when materializing the env var),
//!   asserts exactly one is set, and emits the matching `cargo:rustc-cfg`.
//! - Emits `cargo:rustc-env=<C_NAME>=<value>` for each [`DefineMapping`].
//!
//! The renderer is a pure function over the IR; it does no I/O. Callers
//! decide whether to emit a `build.rs` at all (e.g. `EmitBuildFeatures` skips
//! the call when the IR is empty).

use crate::ir::{BuildConfigIR, ConfigVarKind, ConfigVariable, DefineKind, DefineMapping};

/// Render the entire `build.rs` body for the given [`BuildConfigIR`].
///
/// Returns an empty string when the IR is empty -- `EmitBuildFeatures` does not
/// call into this path for the no-config short-circuit, but we make the
/// behavior explicit here so future callers do not have to reproduce the
/// guard.
pub fn render_build_rs(cfg: &BuildConfigIR) -> String {
    if cfg.is_empty {
        return String::new();
    }

    let mut out = String::new();
    out.push_str("// Auto-generated by HARVEST's emit_build_features tool. Do not edit.\n");
    out.push_str("// Reads CARGO_FEATURE_* variables (set by --features / Cargo.toml)\n");
    out.push_str("// and emits cargo:rustc-cfg / cargo:rustc-env directives.\n\n");
    out.push_str("fn main() {\n");
    out.push_str("    println!(\"cargo:rerun-if-changed=build.rs\");\n");

    // Per-enum-variable block: check-cfg, exactly-one assertion, rustc-cfg
    // emission. Each block binds `let <lower>_value: &str = ...` so composed
    // defines below can substitute the chosen value via `<lower>_value`.
    for var in &cfg.variables {
        if let ConfigVarKind::Enum { values, .. } = &var.kind {
            out.push('\n');
            render_enum_block(&mut out, &var.name, values);
        }
    }

    // Define emissions.
    if !cfg.defines.is_empty() {
        out.push('\n');
        for define in &cfg.defines {
            render_define(&mut out, &cfg.variables, define);
        }
    }

    out.push_str("}\n");
    out
}

/// Render an enum variable's full block: cfg declarations, env reads, assertion,
/// cfg emission, and a binding `let <var>_value: &str = ...` we can use in
/// composed defines.
fn render_enum_block(out: &mut String, var_name: &str, values: &[String]) {
    let cfg_names: Vec<String> = values.iter().map(|v| format!("{var_name}_{v}")).collect();
    let upper = var_name.to_uppercase();
    let lower = var_name.to_lowercase();

    // cargo:rustc-check-cfg=cfg(NAME_a, NAME_b, ...) -- keeps rustc quiet about
    // these cfgs even when no feature selects them.
    out.push_str(&format!(
        "    println!(\"cargo:rustc-check-cfg=cfg({})\");\n",
        cfg_names.join(", ")
    ));

    // Read each CARGO_FEATURE_*.
    for val in values {
        let env = format!("CARGO_FEATURE_{}_{}", upper, val.to_uppercase());
        out.push_str(&format!(
            "    let has_{lower}_{val_lc} = std::env::var(\"{env}\").is_ok();\n",
            val_lc = val.to_lowercase(),
        ));
    }

    // Count active features.
    let active_terms: Vec<String> = values
        .iter()
        .map(|v| format!("has_{lower}_{val_lc} as u32", val_lc = v.to_lowercase()))
        .collect();
    out.push_str(&format!(
        "    let {lower}_active = {};\n",
        active_terms.join(" + ")
    ));
    out.push_str(&format!(
        "    if {lower}_active == 0 {{ panic!(\"one of {} must be enabled\"); }}\n",
        cfg_names.join(", "),
    ));
    out.push_str(&format!(
        "    if {lower}_active > 1 {{ panic!(\"features {} are mutually exclusive\"); }}\n",
        cfg_names.join(", "),
    ));

    // Choose the value and emit cargo:rustc-cfg.
    out.push_str(&format!("    let {lower}_value: &str = "));
    let mut first = true;
    for (val, cfg_name) in values.iter().zip(cfg_names.iter()) {
        let val_lc = val.to_lowercase();
        if first {
            out.push_str(&format!(
                "if has_{lower}_{val_lc} {{ println!(\"cargo:rustc-cfg={cfg_name}\"); \"{val}\" }}",
            ));
            first = false;
        } else {
            out.push_str(&format!(
                " else if has_{lower}_{val_lc} {{ println!(\"cargo:rustc-cfg={cfg_name}\"); \"{val}\" }}",
            ));
        }
    }
    out.push_str(" else { unreachable!() };\n");
}

/// Look up a variable by name in the IR; helper for `render_define`.
fn find_var<'a>(vars: &'a [ConfigVariable], name: &str) -> Option<&'a ConfigVariable> {
    vars.iter().find(|v| v.name == name)
}

/// Returns true if the given variable is an enum-kind variable.
fn is_enum(vars: &[ConfigVariable], name: &str) -> bool {
    matches!(
        find_var(vars, name).map(|v| &v.kind),
        Some(ConfigVarKind::Enum { .. })
    )
}

fn render_define(out: &mut String, vars: &[ConfigVariable], define: &DefineMapping) {
    let c_name = &define.c_name;
    match &define.kind {
        // Bare: `-DNAME=${VAR}` -- emit cargo:rustc-env=NAME=<value>. The value
        // is the just-chosen enum value (numeric or not). Boolean variables are
        // not supported here.
        DefineKind::Bare { var } => {
            if !is_enum(vars, var) {
                return;
            }
            let lower = var.to_lowercase();
            out.push_str(&format!(
                "    println!(\"cargo:rustc-env={c_name}={{}}\", {lower}_value);\n",
            ));
        }
        // QuotedString: `-DNAME="${VAR}"` -- same as bare for build.rs purposes;
        // env vars are plain strings.
        DefineKind::QuotedString { var } => {
            if !is_enum(vars, var) {
                return;
            }
            let lower = var.to_lowercase();
            out.push_str(&format!(
                "    println!(\"cargo:rustc-env={c_name}={{}}\", {lower}_value);\n",
            ));
        }
        // Composed: substitute each `{X}` placeholder with the corresponding
        // `<x>_value` binding.
        DefineKind::Composed { template } => {
            // Build the format string and args by walking `template`.
            let (fmt, args) = compose_format(template, vars);
            if args.is_empty() {
                // Nothing resolvable -- skip rather than emit a literal.
                return;
            }
            out.push_str(&format!(
                "    println!(\"cargo:rustc-env={c_name}={fmt}\", {args});\n",
                args = args.join(", "),
            ));
        }
        // GatedFlag -- feature-gated #define. The Rust side uses
        // `#[cfg(feature = "...")]`, so build.rs has nothing to do here.
        DefineKind::GatedFlag { .. } => {}
    }
}

/// Convert a `{X}_{Y}` template into a (fmt, [args]) pair using `<lower>_value`
/// bindings. Unknown placeholders are emitted as literal text (with format-spec
/// braces escaped). A literal `{` or `}` not associated with a recognized
/// placeholder is escaped to `{{` / `}}` for `println!`.
fn compose_format(template: &str, vars: &[ConfigVariable]) -> (String, Vec<String>) {
    let mut fmt = String::new();
    let mut args: Vec<String> = Vec::new();
    let bytes = template.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        let c = bytes[i];
        if c == b'{' {
            // Find matching `}`.
            if let Some(rel) = template[i + 1..].find('}') {
                let end = i + 1 + rel;
                let name = &template[i + 1..end];
                if is_enum(vars, name) {
                    fmt.push_str("{}");
                    args.push(format!("{}_value", name.to_lowercase()));
                } else {
                    // Unknown placeholder; emit verbatim (escaped for println!).
                    fmt.push_str("{{");
                    fmt.push_str(name);
                    fmt.push_str("}}");
                }
                i = end + 1;
            } else {
                // No matching `}` -- escape and continue.
                fmt.push_str("{{");
                i += 1;
            }
        } else if c == b'}' {
            // Bare '}' must be doubled in a format string.
            fmt.push_str("}}");
            i += 1;
        } else {
            fmt.push(c as char);
            i += 1;
        }
    }
    (fmt, args)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{BuildConfigIR, ConfigVarKind, ConfigVariable, DefineKind, DefineMapping};

    fn example_p02() -> BuildConfigIR {
        BuildConfigIR {
            variables: vec![
                ConfigVariable {
                    name: "APP_MODE".into(),
                    kind: ConfigVarKind::Enum {
                        values: vec!["fast".into(), "safe".into()],
                        numeric: false,
                    },
                    default: Some("fast".into()),
                },
                ConfigVariable {
                    name: "BACKEND".into(),
                    kind: ConfigVarKind::Enum {
                        values: vec!["alpha".into(), "beta".into()],
                        numeric: false,
                    },
                    default: Some("alpha".into()),
                },
                ConfigVariable {
                    name: "ENABLE_EXTRA".into(),
                    kind: ConfigVarKind::Boolean,
                    default: Some("false".into()),
                },
                ConfigVariable {
                    name: "WORD_SIZE".into(),
                    kind: ConfigVarKind::Enum {
                        values: vec!["32".into(), "64".into()],
                        numeric: true,
                    },
                    default: Some("32".into()),
                },
            ],
            defines: vec![
                DefineMapping {
                    c_name: "APP_MODE_STR".into(),
                    kind: DefineKind::QuotedString {
                        var: "APP_MODE".into(),
                    },
                    source_vars: vec!["APP_MODE".into()],
                },
                DefineMapping {
                    c_name: "WORD_SIZE".into(),
                    kind: DefineKind::Bare {
                        var: "WORD_SIZE".into(),
                    },
                    source_vars: vec!["WORD_SIZE".into()],
                },
                DefineMapping {
                    c_name: "BUILD_PROFILE".into(),
                    kind: DefineKind::Composed {
                        template: "{BACKEND}_{WORD_SIZE}".into(),
                    },
                    source_vars: vec!["BACKEND".into(), "WORD_SIZE".into()],
                },
                DefineMapping {
                    c_name: "ENABLE_EXTRA".into(),
                    kind: DefineKind::GatedFlag {
                        gate_var: "ENABLE_EXTRA".into(),
                    },
                    source_vars: vec!["ENABLE_EXTRA".into()],
                },
            ],
            source_selections: vec![],
            conditional_targets: vec![],
            subdir_selections: vec![],
            targets: vec![],
            is_empty: false,
        }
    }

    #[test]
    fn renders_main_skeleton() {
        let out = render_build_rs(&example_p02());
        assert!(out.contains("fn main() {"), "missing fn main(): {out}");
        assert!(out.ends_with("}\n"), "missing closing brace: {out}");
        assert!(
            out.contains("println!(\"cargo:rerun-if-changed=build.rs\");"),
            "missing rerun-if-changed: {out}"
        );
    }

    #[test]
    fn renders_check_cfg_for_each_enum() {
        let out = render_build_rs(&example_p02());
        assert!(out.contains("cargo:rustc-check-cfg=cfg(APP_MODE_fast, APP_MODE_safe)"));
        assert!(out.contains("cargo:rustc-check-cfg=cfg(BACKEND_alpha, BACKEND_beta)"));
        assert!(out.contains("cargo:rustc-check-cfg=cfg(WORD_SIZE_32, WORD_SIZE_64)"));
    }

    #[test]
    fn renders_env_reads_with_cargo_feature_prefix() {
        let out = render_build_rs(&example_p02());
        // Cargo uppercases feature names when surfacing them as env vars.
        assert!(out.contains("CARGO_FEATURE_APP_MODE_FAST"));
        assert!(out.contains("CARGO_FEATURE_APP_MODE_SAFE"));
        assert!(out.contains("CARGO_FEATURE_BACKEND_ALPHA"));
        assert!(out.contains("CARGO_FEATURE_BACKEND_BETA"));
        assert!(out.contains("CARGO_FEATURE_WORD_SIZE_32"));
        assert!(out.contains("CARGO_FEATURE_WORD_SIZE_64"));
    }

    #[test]
    fn renders_rustc_cfg_emissions() {
        let out = render_build_rs(&example_p02());
        assert!(out.contains("cargo:rustc-cfg=APP_MODE_fast"));
        assert!(out.contains("cargo:rustc-cfg=APP_MODE_safe"));
        assert!(out.contains("cargo:rustc-cfg=BACKEND_alpha"));
        assert!(out.contains("cargo:rustc-cfg=BACKEND_beta"));
        assert!(out.contains("cargo:rustc-cfg=WORD_SIZE_32"));
        assert!(out.contains("cargo:rustc-cfg=WORD_SIZE_64"));
    }

    #[test]
    fn renders_mutual_exclusion_panic() {
        let out = render_build_rs(&example_p02());
        assert!(out.contains("mutually exclusive"));
        assert!(out.contains("must be enabled"));
    }

    #[test]
    fn renders_bare_define_for_numeric_var() {
        let out = render_build_rs(&example_p02());
        // -DWORD_SIZE=${WORD_SIZE} becomes a rustc-env emission.
        assert!(
            out.contains("cargo:rustc-env=WORD_SIZE="),
            "missing WORD_SIZE env: {out}"
        );
    }

    #[test]
    fn renders_quoted_string_define() {
        let out = render_build_rs(&example_p02());
        assert!(out.contains("cargo:rustc-env=APP_MODE_STR="));
    }

    #[test]
    fn renders_composed_define() {
        let out = render_build_rs(&example_p02());
        // BUILD_PROFILE composed from BACKEND and WORD_SIZE.
        assert!(out.contains("cargo:rustc-env=BUILD_PROFILE="));
        // Both substituted values must appear as args.
        assert!(out.contains("backend_value"));
        assert!(out.contains("word_size_value"));
    }

    #[test]
    fn gated_flag_does_not_emit_env() {
        let out = render_build_rs(&example_p02());
        // ENABLE_EXTRA is a GatedFlag; no `rustc-env=ENABLE_EXTRA=` should be emitted.
        // (The cfg handling for boolean features uses `#[cfg(feature = "...")]` directly.)
        assert!(!out.contains("cargo:rustc-env=ENABLE_EXTRA="));
    }

    #[test]
    fn empty_ir_renders_empty_string() {
        let ir = BuildConfigIR {
            is_empty: true,
            ..Default::default()
        };
        assert_eq!(render_build_rs(&ir), "");
    }

    #[test]
    fn renders_to_valid_rust_source() {
        // Heuristic check: balanced braces.
        let out = render_build_rs(&example_p02());
        let opens = out.matches('{').count();
        let closes = out.matches('}').count();
        assert_eq!(opens, closes, "unbalanced braces in:\n{out}");
    }
}
